// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiOAd6JVovkDhVEaZIZi54g_vWBKGhMgk',
    appId: '1:316940559783:web:54a3d6e96c2a78abb64282',
    messagingSenderId: '316940559783',
    projectId: 'fir-cloud-messaging-2c74b',
    authDomain: 'fir-cloud-messaging-2c74b.firebaseapp.com',
    storageBucket: 'fir-cloud-messaging-2c74b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3d9KJxdR_o2u-swRvoNlYPE_7ftu9doE',
    appId: '1:316940559783:android:4e3a7cf2d925a962b64282',
    messagingSenderId: '316940559783',
    projectId: 'fir-cloud-messaging-2c74b',
    storageBucket: 'fir-cloud-messaging-2c74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ls6q9gaoZ0x5JMYRWVyvMJXFtM2Jm3Y',
    appId: '1:316940559783:ios:e83a96b1005811b8b64282',
    messagingSenderId: '316940559783',
    projectId: 'fir-cloud-messaging-2c74b',
    storageBucket: 'fir-cloud-messaging-2c74b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ls6q9gaoZ0x5JMYRWVyvMJXFtM2Jm3Y',
    appId: '1:316940559783:ios:e83a96b1005811b8b64282',
    messagingSenderId: '316940559783',
    projectId: 'fir-cloud-messaging-2c74b',
    storageBucket: 'fir-cloud-messaging-2c74b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiOAd6JVovkDhVEaZIZi54g_vWBKGhMgk',
    appId: '1:316940559783:web:01275663446f5e0fb64282',
    messagingSenderId: '316940559783',
    projectId: 'fir-cloud-messaging-2c74b',
    authDomain: 'fir-cloud-messaging-2c74b.firebaseapp.com',
    storageBucket: 'fir-cloud-messaging-2c74b.firebasestorage.app',
  );
}
